name: Build

on:
  push:
    branches-ignore:
      - "azure-*"
    paths-ignore:
      - "*.txt"
      - "*.md"
  # pull_request:
  #   branches-ignore:
  #     - "azure-*"
  #   paths-ignore:
  #     - "*.txt"
  #     - "*.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest]
      fail-fast: false

    env:
      MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

    steps:
      - name: ‚§µÔ∏è Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: üõ†Ô∏è Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          # global-json-file: global.json
          dotnet-version: |
            2.1.x
            3.1.x
            6.0.x
            8.0.100

      - name: üõ†Ô∏è Install dotnet tools
        run: dotnet tool restore

      - name: üéÇ Run cake
        shell: pwsh
        # run: dotnet cake --target=Package --configuration=Release
        run: dotnet cake --target=BuildTestAndPackage --configuration=Release

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: nupkg-files
    #     path: package/*.nupkg
    # - name: Upload MSI artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: msi-files
    #     path: package/*.msi
    # - name: Upload ZIP artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: zip-files
    #     path: package/*.zip
